### ISSUE TITLE
Suggestion: Change description of repository

### ISSUE THREAD

**Issue by RichardLitt** [divvun/giellakbd-ios#1]
Hey there! :wave: Awesome tool. 

I think the description for this repository could be a better better. I suggest: `OSS reimplementation of iOS keyboard with support for localised keyboards.` That might be more useful to newcomers than `Giella keyboard for iOS`. 

Is this part of Giellatekno? I'm not sure what Giella means, and it is hard to tell from the README. 

Thanks.

**Comment by bbqsrc** [comment]
Hey! Thanks for the feedback!

I'll update the description momentarily. I'm wary of using the word 'support' yet because right now this repo is only supported when used with the `kbdgen` tool. I should update the README to explain that though...

I'll speak with @snomos about having a generic blurb about Divvun and related Northern Sami and Norwegian terms that appear in different places, we this code is getting a bit more attention lately (which I'm loving 😄 ).

**Comment by RichardLitt** [comment]
Updating the README should fix that problem. Better to document it somewhere than nowhere. :) 

That would be cool, too. One of the things I've been doing that seems to work well is to have a separate repository - I call it `Welcome`, normally - in an organization that gives a high-level overview of the work going on on the GitHub, and what means what (aka, "this repo is a fork, don't use it", "this repo is deprecated", "this is our main repo.") That might help with some global issues like introducing Sámi tech. 

I found this repo through Giellatekno, which I found through my work on my listing of code for endangered languages at [RichardLitt/endangered-languages](https://github.com/RichardLitt/endangered-languages). I've just finished going through the Divvun org and added what I thought was relevant. Would be great if you could give it a look if there's something I missed! Otherwise, keep up the good work. :)

**Comment by bbqsrc** [comment]
I don't see anything missing, but I'll be sure to ping you if/when we add anything new and notable for that list. Thanks!
