### ISSUE TITLE
4th row not being displayed in most iPads [Bug]

### ISSUE THREAD

**Issue by waelsaad** [divvun/giellakbd-ios#132]
Hi,

I am not sure if I did something wrong but to me there is a bug because you cannot have a 4th row on many of the iPads, like iPad Pro 9.7 and iPad Air and iPad 11 inch, etc...

I think it seems to work only on iPads with 12.9 inch and also for some strange reason on iPad (7th generation).

If possible I would like to have all 4 rows visible as done with the iPhones on all iPads. Thanks

**Comment by snomos** [comment]
I think you may have done something wrong - using the yaml layout files, there's no problem adding a fourth row on the 9.7" iPad:

![IMG_BA757C564A2F-1](https://user-images.githubusercontent.com/1255285/74216087-f9114a80-4cab-11ea-813e-20567a258fbf.jpeg)

That layout is used for all iPads 9.7" and smaller.

The 12" layout, used for all larger iPads, has by definition a fourth row, as the digit row is included by default - it is essentially a copy of the standard ISO keyboard layout. For the SMS language, we have used the fourth row for letters instead of digits, as we also do for the physical ISO keyboard layouts.

**Comment by waelsaad** [comment]
Hmm thank you I will check again ! and let you know.

**Comment by waelsaad** [comment]
Correct, it seems I did something wrong, thanks for confirming.
