### ISSUE TITLE
Latest version needs uninstall to make it work

### ISSUE THREAD

**Issue by albbas** [divvun/giellakbd-ios#186]
After the upgrade to the latest version, when pressing the globus, sami letters aren't activated. The app is installed according to App store. 
The app must be uninstalled, then installed to make it work again. The reporter tells this happened on three devices, an unknown iPhone, an iPhone 6 and the reporter's iPhone 12. 
![received_427413231622120](https://user-images.githubusercontent.com/75695/102695381-409b2800-4227-11eb-8c48-b7d4276868b2.jpeg)

**Comment by bbqsrc** [comment]
That's frustrating. From the crash logs this only seems to be happening to a small subset of users, but fairly consistently. That reinstalling the app fixes it makes absolutely no sense, though.

Worse, it's basically impossible to reproduce this for anybody who has already upgraded, as you can't control the current cache of your phone at all.

What I would suggest to anybody who is complaining about crashes, ask them to open the Divvun Keyboard app, and let me know if that stops the crashes from happening. What I suspect the issue is is that it's a permissions issue with creating new files for the first time, which can only be done from the app. If the keyboard was enabled out of band, well, that might cause this issue. (We tested this and didn't have any issues, but it might be something to do with keyboards being updated from a _super_ old version or similar.)
