### ISSUE TITLE
Taps between keys should trigger closest key

### ISSUE THREAD

**Issue by dylanhand** [divvun/giellakbd-ios#63]
There are several pixels between keys, both horizontally and vertically. Currently, tapping anywhere in these regions does nothing. It should, like the native keyboard, trigger the closest key.

When using the keyboard in a real setting over the weekend I noticed that it was surprisingly easy to miss keys. My typing rate was probably cut in half because of this.

Attached is a screenshot of current dead space.
![Simulator_Screen_Shot_-_iPhone_11_Pro_-_2020-01-10_at_15_39_38_2](https://user-images.githubusercontent.com/431529/72241402-0e308600-35e7-11ea-8933-66e5e6d7e061.png)

**Comment by snomos** [comment]
Very good observation, and it fits well with feedback we have received, where users feel that it is slow and unresponsive to type on compared to Apple's.

Also note that the error models for the keyboard spellers are enhanced with neighbour key errors, so that if the user by accident hit the key to the left or right (or above etc) the speller should be able to suggest the appropriate correction. Thus, there is no reaons to leave any pixel without connection to the nearest key.

**Comment by dylanhand** [comment]
This appears to only affect iPhone in Dark Mode.

**Comment by dylanhand** [comment]
Fixed.

@snomos - do you know if the users who said the keyboard was slow and unresponsive were using dark mode?

In my tests, this bug only affected dark mode.

It will be helpful to know if they found the keyboard slow and unresponsive for a reason other than this issue.
