### ISSUE TITLE
Is it possible to hide the BannerView?

### ISSUE THREAD

**Issue by waelsaad** [divvun/giellakbd-ios#93]
Hi,

Really great library. 

I am just wondering if there is an easy way to completly hide the BannerView on top of the Keyboard as the user typing or in fact completely? as I don't need it at al and its usless in my project please.

If I set the static let bannerHeight: CGFloat = 0 it just stretches the keys which is what I don't want ofcourse.

Thank you

Wael

**Comment by snomos** [comment]
This is a good point, and also relevant for us. There are languages we are going to support for which we have no speller yet.

**Comment by waelsaad** [comment]
That's exactly right. The ancient language I am supporting doesn't have spell check or any need for the BannerView.

**Comment by snomos** [comment]
Could I ask what language you are building a keyboard for?

**Comment by waelsaad** [comment]
Hi @dylanhand,

Thanks for looking into it, I had a look at the 2 files changed and made the same replacement in my project but it seems the the overlay which appears as you press on any key on the top row doesn't appear correctly, I am hoping that ofcourse it will be behave as with the native Apple keyboard and as with the other rows so the overlay will appear correctly on top of the first row with the banner hidden.

Thanks again.

**Comment by waelsaad** [comment]
Could we just make the bannerView transparent?

**Comment by waelsaad** [comment]
I think there are Keyboard limitations but there maybe a workaround according to this, so if someone can hide the bannerView correctly please let us know, thank you:

https://medium.com/@inFullMobile/limitations-of-custom-ios-keyboards-3be88dfb694

![1_afUd8iRJdlwp4ZFTwc0ceQ](https://user-images.githubusercontent.com/4057766/73042613-ededaa80-3eb5-11ea-959f-763039661683.png)

**Comment by waelsaad** [comment]
> Could I ask what language you are building a keyboard for?
The language is a branch of the Hieroglphics Language :)

**Comment by dylanhand** [comment]
Hi @waelsaad,

You're right about the height limitation for iOS keyboard app extensions - we're limited to the area in our keyboard's view, unlike the native keyboard which extends beyond the keyboard's bounds.

This means that, when disabling the banner, we don't have enough room to show `KeyOverlayView`s properly (as you noticed). 

Thanks for starting a discussion about the possible solutions :)

> Could we just make the bannerView transparent? or create a mask around the top banner view to the top of the keyboard?

This unfortunately won't work because a keyboard can't be made transparent -- it will default to the native keyboard color (I tried it and can confirm). Even if it did, I'm not sure it would be possible to forward touch events from out transparent banner to the non-extension view that lies beneath.

> Or create a background layer around the keyboard so it has the grey color so it can be different from the background color around the banner view (which should be clear / transparent)?

I'm not sure I understand. Can you clarify how this might work?

One thing we *can* do is fix the overlay views so they don't look distorted toward the bottom. But we still won't be able to display them above the keyboard's view, which means the user won't really be able to see them anyway since their finger will be in the way.

Another possibility is re-purposing the `BannerView` to display something else that's useful. This would give us the height we need to show the top row `KeyOverlayView`s. Is there something else this area could be used for in the language you're supporting?

Let me know if you have any other ideas for a fix, or if you'd like to experiment and submit a pull request when you've found something that works :)

**Comment by waelsaad** [comment]
Hey @dylanhand , Thank you for the detailed response and trying something, I am out of ideas at the moment in terms of hiding the banner view but if something does come up I'll share it but I doubt it right now due to the limitation, the best thing to do is as you said make use of it somehow, but also if you do come up with anything in the futue also let us know, it will be very helpfull even in the far future :).
