### ISSUE TITLE
Keyboard redraw problem with iPhone SE in iOS 10, 11, 12

### ISSUE THREAD

**Issue by waelsaad** [divvun/giellakbd-ios#99]
I quickly checked and it seems these devices are not yet supported, iPhone 4, 5 and SE

4 and 5 are not a problem because they can be restricted by say targeting iOS 12 as a minimum to allow support for iPhone 6 because it works fine there but with regards to iPhone SE it will be a problem because it can go up to the latest iOS 13.3 and its a smaller device like 4 and 5.

Basically its to do with the fact that there is no BannerView and the overlay of the top buttons are not visible.

**Comment by snomos** [comment]
I will check, but the keyboard should work on small screens like the iPhone SE. Will test it later today on a real device. If it does not work it is a bug.

**Comment by waelsaad** [comment]
Apology its working, I was using an older version because of the other bug I ran into which I already logged, where the overlay of the buttons on the far right don't appear.

**Comment by waelsaad** [comment]
What is the minimum iOS we can target?

**Comment by snomos** [comment]
Our requirement is iOS 10 and newer. But testing on older OS's can be hard, since Apple is so good at pushing updates on people :)

**Comment by waelsaad** [comment]
In Xcode you can download at least one simulator for iPhone SE targeting iOS 10.x and see the behaviour. That should cover all possible scenarios for iOS 10 compatability otherwise it might be rejected by Apple.

**Comment by dylanhand** [comment]
Hi @waelsaad,

I'm having trouble understanding what this issue is referring to. Can you clarify the problem and provide screenshots?

Thanks :)

**Comment by snomos** [comment]
Initial tests on an iPhone SE running iOS 12.3.1 indicated that it works fine:
![IMAGE 2020-01-27 11:32:31](https://user-images.githubusercontent.com/1255285/73163447-b4f14800-40f8-11ea-822d-ad8b9bad2afc.jpg)

But then I turned the phone into horizontal:
![IMAGE 2020-01-27 11:33:07](https://user-images.githubusercontent.com/1255285/73163488-ca667200-40f8-11ea-947b-9e7f2d062ada.jpg)

After dismissing the keyboard, and bringing it back up, it redrew properly. But when I turned the phone back up in regular/portrait orientation, the bug came back:
![IMAGE 2020-01-27 11:34:25](https://user-images.githubusercontent.com/1255285/73163580-f97ce380-40f8-11ea-809a-9550ae826b3c.jpg)

Other than this pretty serious redraw/update bug, it worked fine, suggestions and all.

**Comment by bbqsrc** [comment]
@dylanhand looks like more delicious drawing regressions?

**Comment by dylanhand** [comment]
Good find @snomos - I'll have a look.

@bbqsrc 😋

**Comment by bbqsrc** [comment]
[laughs in layout constraints]

**Comment by snomos** [comment]
I noticed the same redraw problems on an iPhone XS Max (iOS 13.3) and on an iPad 9.7" (iOS 13.1.2). Latest build (117).

**Comment by dylanhand** [comment]
Confirmed not working on iPhone XS Max in iOS 13.3:

![Screen Shot 2020-01-28 at 2 07 15 PM](https://user-images.githubusercontent.com/431529/73266620-85fdd380-41d7-11ea-9f97-aed5f0ece9c4.png)
